### ISSUE TITLE
请问缓存是怎么做的？

### ISSUE THREAD

**Issue by ittianyu** [LuoboDcom/ZZShow#1]
对于新闻类的app，一直在考虑缓存怎么做。
先说一下我的策略：无论是否存在缓存，都去请求网络。也就是先显示缓存数据，然后请求网络，显示最新的数据。

粗略看了一下博主的代码，没找到缓存的代码，麻烦楼主介绍一下。

**Comment by LuoboDcom** [comment]
我这里就是直接利用Okhttp的缓存策略的，你可以看下 如下这个类：https://github.com/LuoboDcom/ZZShow/blob/master/app/src/main/java/com/ys/yoosir/zzshow/utils/httputil/OkHttpUtil.java

**Comment by ittianyu** [comment]
基本知道了，设置过期时间，根据网络状况做缓存，学习了，不过用拦截器来做感觉不太优雅。
我一般是建立一个远程仓库，一个本地仓库，方便针对不同的接口做调整，比如某些接口没必要缓存，只缓存第一页之类的。

**Comment by LuoboDcom** [comment]
@ittianyu 是的，代码里面是动态的设置缓存的，就是Header。像你说的，只缓存第一页数据也是可以的，因为它是通过URL的hashCode 做key存储的，第一页与加载更多的URL是不同的。用拦截器的确是不优雅。这有一篇文章你可以看下 http://www.jianshu.com/p/9cebbbd0eeab
