### ISSUE TITLE
新闻切换到夜间模式就有问题

### ISSUE THREAD

**Issue by chenlindaydayup** [LuoboDcom/ZZShow#2]

**Comment by LuoboDcom** [comment]
可以描述一下问题的情况吗？

**Comment by chenlindaydayup** [comment]
你选新闻选项  然后切换夜间模式  新闻就会成无数据  点下置顶程序奔溃

**Comment by LuoboDcom** [comment]
我刚刚试了下，我这边是正常的，这个问题有点难从先。如果你有fork我的代码，你可以打印log，看下recreate后，调用顺序 onSaveInstanceState -> onCreate -> initViews() ->setDefaultChildFragment -> setChildFragment()，先看下
childFragmentType 的值是多少，然后setChildFragment后，NewsFragment有没有调用。抱歉！

**Comment by WangChangQin** [comment]
确实有问题的，我这边也是，赶快修复吧作者大大

**Comment by LuoboDcom** [comment]
@WangChangQin 可以描述下，你的操作步骤吗？

**Comment by WangChangQin** [comment]
就是从github上down了你的代码，然后编译到手机上，当打开app，点夜间模式的时候，新闻页面就会是蓝色背景，没有数据，当你在切回来的时候还是不行。你白天模式甚至点击下新闻，都会跳到图片，感觉问题还是挺多的

**Comment by LuoboDcom** [comment]
@chenlindaydayup  @WangChangQin Bug 已经修改完了，并添加了一个 APK 下载。谢谢你们的反馈！
